version: '3.8'

services:
  robokinematics-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Persist SQLite Database externally so saving restarts don't lose data
      - ./backend/robokinematics.db:/app/backend/robokinematics.db
    environment:
      - NODE_ENV=production
